name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      DOTNET_NOLOGO: true
    steps:
    - name: Clone source
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --property Version=${{ github.event.release.tag_name }}

    - name: Sign .NET Standard 2.0 library
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/netstandard2.0/Hyphen.Sdk.dll
        output_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/netstandard2.0/signed
        malware_block: false
        environment_name: PROD

    - name: Sign .NET 8 library
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/net8.0/Hyphen.Sdk.dll
        output_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/net8.0/signed
        malware_block: false
        environment_name: PROD

    - name: Replace unsigned binaries with signed binaries
      run: |
        cp src/Hyphen.Sdk/bin/Release/netstandard2.0/signed/Hyphen.Sdk.dll src/Hyphen.Sdk/bin/Release/netstandard2.0/
        cp src/Hyphen.Sdk/bin/Release/net8.0/signed/Hyphen.Sdk.dll src/Hyphen.Sdk/bin/Release/net8.0/

    - name: Package
      run: dotnet pack --no-build --version ${{ github.event.release.tag_name }}

    - name: Sign package
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/Hyphen.Sdk.${{ github.event.release.tag_name }}.nupkg
        output_path: ${GITHUB_WORKSPACE}/artifacts
        malware_block: false
        environment_name: PROD

    - name: Publish
      run: dotnet nuget push artifacts/Hyphen.Sdk.${{ github.event.release.tag_name }}.nupkg -s https://api.nuget.org/v3/index.json -k {{ secrets.NUGET_API_KEY }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: packages
        path: artifacts
        compression-level: 9
