name: tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      DOTNET_NOLOGO: true
    steps:
    - name: Clone source
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Get .NET info
      run: dotnet --info
      continue-on-error: true

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests with coverage
      run: dotnet test --no-build --configuration Release --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --report-ctrf --report-ctrf-filename tests.ctrf

    - name: Generate coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: test/Hyphen.Sdk.Tests/bin/Release/net8.0/TestResults/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: file

    - name: Publish test results report as Actions build summary
      uses: ctrf-io/github-test-reporter@v1
      if: always()
      with:
        report-path: test/Hyphen.Sdk.Tests/bin/Release/net8.0/TestResults/tests.ctrf
        github-report: true
        title: 'Test summary'

    - name: Publish coverage report to summary
      if: always()
      run: |
        echo "## Coverage summary" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Upload test artifacts
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: test-results
        path: |
          test/Hyphen.Sdk.Tests/bin/Release/net8.0/TestResults/coverage.cobertura.xml
          test/Hyphen.Sdk.Tests/bin/Release/net8.0/TestResults/tests.ctrf

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --property Version=0.0.1

    - name: Sign .NET Standard 2.0 library
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/netstandard2.0/Hyphen.Sdk.dll
        output_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/netstandard2.0/signed
        malware_block: false
        environment_name: PROD

    - name: Sign .NET 8 library
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/net8.0/Hyphen.Sdk.dll
        output_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/net8.0/signed
        malware_block: false
        environment_name: PROD

    - name: Replace unsigned binaries with signed binaries
      run: |
        cp src/Hyphen.Sdk/bin/Release/netstandard2.0/signed/Hyphen.Sdk.dll src/Hyphen.Sdk/bin/Release/netstandard2.0/
        cp src/Hyphen.Sdk/bin/Release/net8.0/signed/Hyphen.Sdk.dll src/Hyphen.Sdk/bin/Release/net8.0/

    - name: Package
      run: dotnet pack --no-build --version 0.0.1

    - name: Sign package
      uses: sslcom/esigner-codesign@develop
      with:
        command: sign
        username: ${{ secrets.ES_USERNAME }}
        password: ${{ secrets.ES_PASSWORD }}
        credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
        totp_secret: ${{ secrets.ES_TOTP_SECRET }}
        file_path: ${GITHUB_WORKSPACE}/src/Hyphen.Sdk/bin/Release/Hyphen.Sdk.0.0.1.nupkg
        output_path: ${GITHUB_WORKSPACE}/artifacts
        malware_block: false
        environment_name: PROD

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: artifacts
        compression-level: 9
